- name: Configure Flask dependencies
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Install dependencies
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - wget
        - python3
        - python3-pip
        

    - name: Clone repository
      git: 
        repo: 'https://github.com/sergargar/IPReflector-Service.git'
        dest: /etc/IPReflector
        update: yes

    - name: Install Flask and Gunicorn
      command: pip3 install flask gunicorn
    
    